on: 
  push:
    branches:
      - pruebas
name: 🚀 Desplegar on push pruebas
jobs:
  web-deploy:
    name: 🎉 Despliegue
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener ultimas actualizaciones de codigo
      uses: actions/checkout@v2
    
    - name: 📂 Sincronizar archivos
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        server-dir: /public_html/pruebas.jrcoding.net/